server:
  port: 8080
  context-path: "/"
 
spring:
  application:
    name: Student Course Selection Service
  profiles:
    active: h2
 
---
spring:
  profiles: h2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: h2
    show-sql: true
#    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
